name: Deploy WaterSensor on Environment

on:
  workflow_dispatch:
    inputs:
      serial_port:
        required: false
        type: string
      environment:
        required: true
        type: choice
        options:
          - Home

permissions:
  contents: read
  deployments: write

jobs:
  deployment:
    uses: Zefek/GithubActions/.github/workflows/arduino-build-deploy.yml@3cd03fcde2e3f0c6716a7b5372ee2bf2951d45a6
    with:
      environment: ${{ inputs.environment }}
      serial_port: ${{ inputs.serial_port }}
      device_name: WaterSensor
      source_dir:  "./src/WaterSensor"
      ota:         true

